services:
  ics-gate:
    build: .
    container_name: ics-gate
    ports:
      - "5800:5800"
    environment:
      - CONFIG_PATH=/config/config.yml
      - DB_PATH=/data/icsgate.db
      - TIMEZONE_DEFAULT=UTC
    volumes:
      - ./data:/data         # папка для БД
      - ./config:/config:ro  # папка конфига
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5800/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
